start_animation:
  name: Start Animation
  description: Start an animation
  fields:
    name:
      name: Name
      description: Unique ID for the animation, to be used to turn it off later
      example: "Spooky"
      required: True
      selector:
        text:
    priority:
      name: Priority
      description: Sets a priority for this animation. If multiple animations use the same light, the one with the higher priority will "win" and take control of the light.
      required: True
      example: 100
      default: 0
      selector:
        number:
          min: -100
          max: 100
          step: 1
    transition:
      name: Transition
      description: How long a light should take to transition from it's former state to it's new state.
      example: 1
      required: True
      default: 1
      selector:
        number:
          min: 0
          max: 120
          step: 0.1
          unit_of_measurement: seconds
    change_frequency:
      name: Change Frequency
      description: How often the animation should change something. Lower values means things will be changing faster, which requires higher system specs.
      example: 1
      required: False
      default: 1
      selector:
        number:
          min: 0.5
          max: 3600
          step: 1
    change_amount:
      name: Change Amount
      description: How many lights should be changed each time the frequency is hit. Specifying the word 'all' will change all lights.
      default: all
      selector:
        text:
    ignore_off:
      name: Ignore if Off
      description: If a light in the animation list is off, turn it on.
      example: True
      required: True
      default: True
      selector:
        boolean:
    restore:
      name: Restore State at Animation End
      description: When the animation ends, restore lights to their prior state.
      example: True
      required: True
      default: True
      selector:
        boolean:
    restore_power:
      name: Restore Power at Animation End
      description: When the animation ends, turn any lights that were off back to off.
      example: True
      required: True
      default: False
      selector:
        boolean:

    change_sequence:
      name: Change in Sequence
      description: If set to true, then color changes will happen in order. If set to false, colors will be chosen randomly from the list.
      default: False
      required: True
      selector:
        boolean:
    animate_brightness:
      name: Animate Brightness
      description: Whether or not to animate the brightness. If set to false, brightness will be set once upon startup.
      default: True
      required: True
      selector:
        boolean:
    animate_color:
      name: Animate Colors
      description: Whether or not to animate the colors. If set to false, colors will be set once upon startup.
      default: True
      required: True
      selector:
        boolean:
    lights:
      name: Lights
      description: The lights to include in the animation
      required: True
      selector:
        entity:
          domain: light
          multiple: True
    colors:
      name: Colors
      description: The list of colors. Due to limitations in Home Assistant, you will need to specify this in YAML form. See the documentation for details.
      selector:
        object:
      required: True
      default:
        - color_type: rgb_color
          color: [255, 0, 0]
          brightness: [0, 255]
          one_change_per_tick: True
          nearby_colors: 0
          weight: 10

stop_animation:
  name: Stop Animation
  description: Stop the animated lights
  fields:
    name:
      name: Name
      description: Unique ID for the animation, used when starting it.
      example: "Spooky"
      required: True
      selector:
        text:

remove_lights:
  name: Remove Lights
  description: Remove specified lights from all animations. Stop the animation if there are no lights left in it.
  fields:
    lights:
      name: Lights
      description: The lights to stop animating
      required: True
      selector:
        entity:
          domain: light
          multiple: True
    skip_restore:
      name: Skip Restore State at Animation End
      description: If set to true, do not restore the lights to their prior state even if the animation is configured to do so.
      required: False
      default: False
      selector:
        boolean: {}

add_lights_to_animation:
  name: Add Lights to Animation
  description: Add specified lights to an existing animation.
  fields:
    lights:
      name: Lights
      description: The lights to add to the animation
      required: True
      selector:
        entity:
          domain: light
          multiple: True
    name:
      name: Animated Scene Name
      description: Unique ID for the animation, must already be running. Must give name or select animated scene switch to add lights to but not both.
      example: "Spooky"
      required: False
      selector:
        text:
    animated_scene_switch:
      name: Animated Scene Switch
      description: The selected Animated Scene must already be running. Must give name or select animated scene switch to add lights to but not both.
      required: False
      selector:
        entity:
          filter:
            domain: switch
            integration: animated_scenes
